import Head from 'next/head'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
const inter = Inter({ subsets: ['latin'] })
export default function Home() {
  return (
    <>
      <Head>
        <title>Hunting Coder</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <meta name='keywords' content='next js , hunting coder , huntingCoder blog' />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <div className={styles.cen}>
          <img className={styles.myimg} src='/h.png' alt='missing' height={100} width={134} />
        </div>
        <h1 className={styles.huntingHead}>
          <span className=''>
            &lt;Hunting Coder  /&gt;
          </span>
        </h1>
        <div className={styles.js}>
          <h3>How to learn javaScript in 2023?</h3>
          <p>Javascript is the language used to design web logic.</p>
          <br></br>

          <button className={styles.submit}>Read More</button>
          <br></br>
          <br></br>
        <br></br>
        </div >
        <div className={styles.js}>
          <h3>How to learn javaScript in 2023?</h3>
          <p>Javascript is the language used to design web logic.</p>
          <br></br>

          <button className={styles.submit}>Read More</button>
          <br></br>
          <br></br>
          <br></br>
        </div >
        <div className={styles.js}>
          <h3>How to learn javaScript in 2023?</h3>
          <p>Javascript is the language used to design web logic.</p>
          <br></br>

          <button className={styles.submit}>Read More</button>
          <br></br>
          <br></br>
          <br></br>
        </div>
        <div className={styles.js}>
          <h3>How to learn javaScript in 2023?</h3>
          <p>Javascript is the language used to design web logic.</p>
          <br></br>

          <button className={styles.submit}>Read More</button>
          <br></br>
          <br></br>
          <br></br>
        </div>
      </main>
    </>
  )
}
