import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
// import styles1 from '@/styles/Home1.module.css'
// import styles2 from '@/styles/Home2.module.css'

import Link from 'next/link'
// import Script from 'next/script'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  console.log(styles)
  return (
    <>
      <Head>
        <title>Hunting Coder</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <meta name='keywords' content='next js , hunting coder , huntingCoder blog' />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* <Script  src='/sc.js' strategy='lazyOnload'></Script> */}

      <nav className={styles.mainnav}>
        <ul>
          <Link href='/' >
          <li>Home</li>
          </Link>

          <Link href='/about' >
           <li>About</li>
          </Link>

          <Link href='/contact'>
           <li>Contact</li>
          </Link>

          <Link href='/blog'>
            <li>Blog</li>
          </Link>
        </ul>
      </nav>


      <main className={`${styles.main} ${inter.className}`}>

        <main >
          <h1 className={styles.huntingHead}> Hunting Coder </h1>
          <h2>Popular Blogs</h2><br></br>

          <div>
            <h3>How to learn javaScript in 2023?</h3>
            <p>Javascript is the language used to design web logic.</p>
          </div>
          <br></br>

          <div>
            <h3>How to learn javaScript in 2023?</h3>
            <p>Javascript is the language used to design web logic.</p>
            <br></br>
          </div>
          <div>
            <h3>How to learn javaScript in 2023?</h3>
            <p>Javascript is the language used to design web logic.</p>
            <br></br>
          </div><div>
            <h3>How to learn javaScript in 2023?</h3>
            <p>Javascript is the language used to design web logic.</p>
            <br></br>
          </div>


        </main>






        <div className={styles.center}>
          <Image
            className={styles.logo}
            src="/next.svg"
            alt="Next.js Logo"
            width={180}
            height={37}
            priority
          />
        </div>


      </main>
    </>
  )
}
